# Generated by Django 5.0 on 2023-12-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
